const { ChatGroq } = require("@langchain/groq");
const { SystemMessage, AIMessage } = require("@langchain/core/messages");
const { createReactAgent } = require("@langchain/langgraph/prebuilt");
const { MemorySaver } = require("@langchain/langgraph");
const { ragSearchTool } = require("../tools/ragSearchTool");
const { registryTool } = require("../tools/registryTool");
const { calculatorTool } = require("../tools/calculatorTool");

/**
 * Wraps a ChatGroq LLM to intercept 400 BadRequestErrors (e.g. tool_use_failed)
 * and automatically retry the call.
 */
function wrapLlmForGroqRobustness(llm) {
  const originalInvoke = llm.invoke.bind(llm);
  const originalBindTools = llm.bindTools.bind(llm);

  llm.invoke = async function (input, options) {
    let attempts = 3;
    for (let i = 0; i < attempts; i++) {
      try {
        return await originalInvoke(input, options);
      } catch (error) {
        const isToolError = error?.message?.includes("Failed to call a function") || 
                            error?.message?.includes("tool_use_failed") ||
                            error?.status === 400;
        if (isToolError && i < attempts - 1) {
          console.warn(`[GroqLLM] ⚠️ API tool calling error detected (400). Retrying invocation: attempt ${i + 2}/${attempts}...`);
          continue;
        }
        throw error;
      }
    }
  };

  llm.bindTools = function (tools, options) {
    const bound = originalBindTools(tools, options);
    const originalBoundInvoke = bound.invoke.bind(bound);

    bound.invoke = async function (input, options) {
      let attempts = 3;
      for (let i = 0; i < attempts; i++) {
        try {
          return await originalBoundInvoke(input, options);
        } catch (error) {
          const isToolError = error?.message?.includes("Failed to call a function") || 
                              error?.message?.includes("tool_use_failed") ||
                              error?.status === 400;
          if (isToolError && i < attempts - 1) {
            console.warn(`[GroqLLM-Bound] ⚠️ API tool calling error detected in bound model. Retrying: attempt ${i + 2}/${attempts}...`);
            continue;
          }
          throw error;
        }
      }
    };

    return bound;
  };

  return llm;
}

/**
 * Sanitizes, maps, and validates tool calls generated by the LLM.
 * Detects and breaks infinite tool-calling loops.
 */
function postModelHook(state) {
  const { messages } = state;
  if (!messages || messages.length === 0) return {};

  const lastMessage = messages[messages.length - 1];

  // Only intercept AIMessages that contain tool calls or invalid tool calls
  if (lastMessage && lastMessage._getType() === "ai" && (
    (lastMessage.tool_calls && lastMessage.tool_calls.length > 0) ||
    (lastMessage.invalid_tool_calls && lastMessage.invalid_tool_calls.length > 0)
  )) {
    let modified = lastMessage.invalid_tool_calls && lastMessage.invalid_tool_calls.length > 0;
    let loopDetected = false;
    let fallbackContent = "";

    const correctedToolCalls = [];

    // Parse and combine both valid and invalid tool calls
    const rawToolCalls = [
      ...(lastMessage.tool_calls || []),
      ...(lastMessage.invalid_tool_calls || []).map(itc => {
        let parsedArgs = itc.args;
        if (typeof itc.args === 'string') {
          try {
            parsedArgs = JSON.parse(itc.args);
          } catch (e) {
            parsedArgs = itc.args; // keep as string if not valid JSON
          }
        }
        return {
          ...itc,
          args: parsedArgs
        };
      })
    ];

    for (const tc of rawToolCalls) {
      let name = tc.name;
      let args = tc.args;
      if (args === null || args === undefined) {
        args = {};
      }

      // 1. Map tool name aliases (hallucinated names)
      if (["calculator", "calc", "math", "calculatorTool"].includes(name)) {
        name = "calculator_tool";
        modified = true;
      } else if (["search", "rag_search", "ragSearchTool", "searchKnowledgeBase", "search_kb"].includes(name)) {
        name = "search_knowledge_base";
        modified = true;
      } else if (["registry", "registryTool", "document_registry"].includes(name)) {
        name = "registry_tool";
        modified = true;
      }

      // 2. Normalize arguments mapping
      if (name === "calculator_tool") {
        if (typeof args === "string") {
          args = { expression: args };
          modified = true;
        } else if (!args.expression && Object.keys(args).length > 0) {
          const key = Object.keys(args)[0];
          args = { expression: String(args[key]) };
          modified = true;
        }
      } else if (name === "search_knowledge_base") {
        if (typeof args === "string") {
          args = { query: args };
          modified = true;
        } else if (!args.query && Object.keys(args).length > 0) {
          const key = Object.keys(args)[0];
          args = { query: String(args[key]) };
          modified = true;
        }
      }

      // 3. Loop detection: Check if this tool call with exact same arguments was already executed
      const isDuplicate = messages.slice(0, -1).some(msg => {
        if (msg._getType() === "ai" && msg.tool_calls && msg.tool_calls.length > 0) {
          return msg.tool_calls.some(prevCall => {
            const mappedPrevName = ["calculator", "calc", "math", "calculatorTool"].includes(prevCall.name) ? "calculator_tool" :
                                   ["search", "rag_search", "ragSearchTool", "searchKnowledgeBase"].includes(prevCall.name) ? "search_knowledge_base" :
                                   ["registry", "registryTool", "document_registry"].includes(prevCall.name) ? "registry_tool" : prevCall.name;
            return mappedPrevName === name && JSON.stringify(prevCall.args) === JSON.stringify(args);
          });
        }
        return false;
      });

      if (isDuplicate) {
        console.warn(`[postModelHook] 🛑 Infinite loop detected: tool "${name}" already called with args:`, args);
        loopDetected = true;
        
        // Find the last output of this tool in the conversation to use as fallback content
        for (let i = messages.length - 2; i >= 0; i--) {
          if (messages[i]._getType() === "tool" && (messages[i].name === name || messages[i].name === tc.name)) {
            // Strip the boilerplate text to get the raw result if it's calculator
            let content = messages[i].content || "";
            if (name === "calculator_tool" && content.includes("Result of ")) {
              const parts = content.split(" = ");
              if (parts.length > 1) content = parts[1];
            }
            fallbackContent = content;
            break;
          }
        }
        
        if (!fallbackContent) {
          fallbackContent = `I have already executed the search or calculation for this request.`;
        }
        
        continue; // Skip adding this tool call to prevent it from running again
      }

      correctedToolCalls.push({
        ...tc,
        name,
        args
      });
    }

    // If we changed any tool calls or skipped duplicates
    if (modified || loopDetected) {
      // If we filtered out all tool calls due to loop detection, provide the fallback content
      const finalContent = loopDetected && correctedToolCalls.length === 0 ? fallbackContent : lastMessage.content;
      
      const updatedMessage = new AIMessage({
        content: finalContent,
        tool_calls: correctedToolCalls.length > 0 ? correctedToolCalls : undefined,
        id: lastMessage.id
      });

      console.log(`[postModelHook] 🔄 Updating AIMessage. Loop broke: ${loopDetected}. Tool calls: ${correctedToolCalls.length}`);
      return { messages: [updatedMessage] };
    }
  }

  return {};
}

/**
 * Initializes and returns the Agent Executor using LangGraph.
 */
function createMainAgent() {
  if (!process.env.GROQ_API_KEY) {
    throw new Error("GROQ_API_KEY is not defined in environment variables.");
  }

  // 1. Initialize and wrap the Chat Model
  const rawLlm = new ChatGroq({
    apiKey: process.env.GROQ_API_KEY,
    model: process.env.GROQ_MODEL || "llama-3.1-8b-instant",
    temperature: 0.0, // Set to 0.0 for maximum determinism and format compliance
    maxTokens: 800,
  });

  const llm = wrapLlmForGroqRobustness(rawLlm);

  // 2. Define the Tools available to the Agent
  const tools = [ragSearchTool, registryTool, calculatorTool];

  const systemPrompt = `You are Ethereal, an intelligent AI Assistant.
You have access to tools that can search the knowledge base, list available documents in the registry, and perform mathematical calculations.

Answer the user's queries concisely and accurately. Respond directly with the final answer when you have it. If you don't know the answer, just say so.

You must invoke tools using standard JSON format only. Do not use XML-like tags or custom function-calling wrappers.`;

  // 4. Create a Checkpointer for conversational memory
  const checkpointer = new MemorySaver();

  // 5. Create the Tool Calling Agent using LangGraph prebuilt agent
  const agentExecutor = createReactAgent({
    llm,
    tools,
    prompt: systemPrompt, // Use modern 'prompt' instead of deprecated 'messageModifier'
    postModelHook,
    checkpointSaver: checkpointer,
  });

  return agentExecutor;
}

module.exports = {
  createMainAgent,
  postModelHook,
  wrapLlmForGroqRobustness,
};
